### PR TITLE
specify ambiguous routes

### PR DESCRIPTION
**Pull request by nverwer**
When a path is ambiguous, log the matching routes.

### CODE REVIEW

**Review by tuurma — APPROVED** [review]

**Comment by line-o** [comment]
Test are failing. I will check locally what is going wrong.

**Comment by line-o** [comment]
With eXist-7.0.0-SNAPSHOT we have 11 failing tests (custom authorisation and file upload are affected it seems).

**Comment by line-o** [comment]
I revisited and tested my proposal and came up with

```xquery
util:log("debug", map {
  "ambiguous route" : $request-data?path,
  "matching definitions" : array { $matching-routes?path }
})
```

Which would give us 

```
2023-07-13 15:41:16,213 [qtp345780740-246] DEBUG  (LogFunction.java [writeLog]:205) - (Line: 117 /usr/local/exist/etc/../data/expathrepo/roaster-1.8.1/content/router.xql) map{"ambiguous route":"/api/errors/handle","matching definitions":("/api/errors/handle","/api/errors/handle")}
```

@nverwer would that be enough information to determine which route definitions are ambigous or do you need more?

**Comment by line-o** [comment]
I just see that the path is not good enough as both are steh same when in fact it is to different ones. And the specificity and priority might be of interest as well.

**Comment by nverwer** [comment]
Hello @line-o , Since the information about ambiguities is primarily interesting for developers, I would indeed want to see the specificity and priority of the matching routes. So how about something like
```
util:log("debug", map {
  "ambiguous route" : $request-data?path,
  "matching definitions" : array { $matching-routes }
})
```
without the path?

I did not actually try this (yet).

**Comment by line-o** [comment]
@nverwer and I put our heads together and came up with this solution:

```
map{
    "ambiguous route":"/api/errors/handle",
    "method": "get",
    "matching definitions":[
        map{
            "priority": 1,
            "specificity": 11,
            "pattern": "/api/errors"
        },
        map{
            "priority": 1,
            "specificity": 18,
            "pattern": "/api/errors/handle"
        }
    ]
}
```

will be logged for the one (test-)request that matches two routes.

**Pull request merged**
