### PR TITLE
improve tests; npm and gulp tasks

### PR DESCRIPTION
**Pull request by line-o**
- drop .existdb.json and put all necessary package metadata in a property `app` in package.json

npm packages are implicitly allowed to add their custom properties package.json but have to take care themselves not to clash with names used by npm. I have use app for other projects.

- adopt [readOptionsFromEnv](https://github.com/eXist-db/gulp-exist#existreadoptionsfromenv) to allow all npm and gulp scripts to target different existdb instances

refs #16 

- enable the custom api with middleware and token authentication by default
- missing tests for middleware, x-constraints and custom authentication
- allow tests on localhost to connect without a proper certificate 
- create XAR-packages in dist folder
- prepend calls in npm scripts with dotenv where applicable. Read
  .env-files to allow setting different connection to the DB instances.
- add npm task "develop" (running gulp default task)
- rename npm script test:build to test:install
- add dependency dotenv-cli
- update dependencies @existdb/gulp-exist and @existdb/gulp-replace-tmpl

### CODE REVIEW

**Comment by line-o** [comment]
This PR needs to be split into two because installation of the crypto-lib, which exist-jwt depends on seems to fail on docker at the moment.

**Comment by joewiz** [comment]
@line-o These sound like great enhancements - and I also appreciated the description of them that you added to https://github.com/eXist-db/exist-markdown/pull/15#issuecomment-1033532879. 

Could you expand a bit on the docker failures you're seeing with crypto-lib? The links here in GitHub to the CI failures seem not to contain the logs. With more info/context, perhaps other folks could help.

**Comment by line-o** [comment]
It turned out that the public-repo instance currently installed on exist-db.org is the culprit that leads to failing installations of dependent packages. This then leads to failing tests in CI.
see https://github.com/eXist-db/public-repo/issues/74 and https://github.com/eXist-db/node-exist/issues/222

**Comment by line-o** [comment]
Hooray! The test application installs and tests are passing!

**Pull request merged**
